### ISSUE TITLE
Fix readthedocs build

### ISSUE THREAD

**Issue by stinovlas** [pawamoy/django-appsettings#100]
https://django-appsettings.readthedocs.io/ currently reports 404 Not Found. I don't think we changed anything, but we should take a look at it and fix it.

**Comment by stinovlas** [comment]
It seems that I don't have enough permissions to set up readthedocs webhook. Maybe @pawamoy will have to set up the readthedocs integration under his account.

**Comment by pawamoy** [comment]
I've recreated the project on RTD and added you as a maintainer. I think we'll need this in the repo:

```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
# formats:
#    - pdf
#    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
# python:
#    install:
#    - requirements: docs/requirements.txt
```

Also, build failed: https://readthedocs.org/projects/django-appsettings/builds/21718297/

Probably changes required by new Sphinx version.
